GET http://localhost:3000/

###

POST http://localhost:3000/register
Content-Type: application/json

{
    "name": "testName",
    "password": "testPassword"
}

###

POST http://localhost:3000/login
Content-Type: application/json

{
    "name": "testName",
    "password": "testPassword"
}

###

GET http://localhost:3000/users

###

POST http://localhost:3000/authenticate
Content-Type: application/json

{
    "name": "testUser",
    "password": "Password"
}